import { combineReducers } from 'redux';
import {
    account,
    auth,
    cart,
    category,
    checkout,
    collection,
    common,
    employee,
    food,
    foodManager,
    history_import,
    ingredients,
    order,
    order_profile,
    payment,
    sources,
    voucher,
    documentManager,
    voucher_admin,
    homepage,
    search,
    ingredient_use,
    recipe,
    ingredientsError,
    dashboard,
} from '.';

const rootReducers = combineReducers({
    [auth.name]: auth.default.reducer,
    [common.name]: common.default.reducer,
    [collection.name]: collection.default.reducer,
    [food.name]: food.default.reducer,
    [category.name]: category.default.reducer,
    [cart.name]: cart.default.reducer,
    [foodManager.name]: foodManager.default.reducer,
    [ingredients.name]: ingredients.default.reducer,
    [sources.name]: sources.default.reducer,
    [account.name]: account.default.reducer,
    [payment.name]: payment.default.reducer,
    [voucher.name]: voucher.default.reducer,
    [checkout.name]: checkout.default.reducer,
    [employee.name]: employee.default.reducer,
    [order.name]: order.default.reducer,
    [documentManager.name]: documentManager.default.reducer,
    [voucher_admin.name]: voucher_admin.default.reducer,
    [history_import.name]: history_import.default.reducer,
    [homepage.name]: homepage.default.reducer,
    [order_profile.name]: order_profile.default.reducer,
    [search.name]: search.default.reducer,
    [ingredient_use.name]: ingredient_use.default.reducer,
    [recipe.name]: recipe.default.reducer,
    [ingredientsError.name]: ingredientsError.default.reducer,
    [dashboard.name]: dashboard.default.reducer,
});

export type RootReducerType = ReturnType<typeof rootReducers>;

export default rootReducers;
