name: Notify Slack on GitHub Events

on:
  push:
  pull_request:
  issues:
  issue_comment:
  release:
  workflow_run:
    workflows: ["Build and Test"]
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_KEY }}
          SLACK_USERNAME: "GitHub Bot"
          SLACK_ICON_EMOJI: ":octocat:"
          SLACK_COLOR: "#36a64f"
          SLACK_MESSAGE: >
            *${{ github.event_name }}* event triggered by *${{ github.actor }}* on *${{ github.repository }}*
            - Event: `${{ github.event_name }}`
            - Ref: `${{ github.ref }}`
            - Commit: `${{ github.sha }}`
            - URL: https://github.com/${{ github.repository }}/commit/${{ github.sha }}
